#!/usr/bin/env perl
#
# zsh の HISTFILE から、指定された「エントリ開始の物理行番号」のエントリを
# 行末 \ の継続行ごとまるごと削除する。
# zsh-env-history-list が出力する行番号を、fzf の Ctrl-D バインドから受け取る。
#
# 行番号で消すので、Meta エンコードされた日本語や複数行コマンドでも
# 文字列一致に失敗せず確実に削除できる。
#
use strict;
use warnings;

my $target = shift;
exit 0 unless defined $target && $target =~ /^\d+$/;

my $hf = $ENV{HISTFILE} || "$ENV{HOME}/.zsh_history";
open(my $fh, '<:raw', $hf) or exit 0;
my @lines = <$fh>;
close($fh);

my $start = $target - 1;                            # 0 始まり
exit 0 if $start < 0 || $start > $#lines;
exit 0 unless $lines[$start] =~ /^: \d+:\d+;/;      # 開始行でなければ安全のため何もしない

# 次のタイムスタンプ行の手前まで (= 継続行) を範囲に含める
my $end = $start;
$end++ while ($end < $#lines && $lines[$end + 1] !~ /^: \d+:\d+;/);

splice(@lines, $start, $end - $start + 1);

my $tmp = "$hf.tmp.$$";
open(my $out, '>:raw', $tmp) or exit 0;
print $out @lines;
close($out)        or do { unlink $tmp; exit 1 };
rename($tmp, $hf)  or do { unlink $tmp; exit 1 };
